services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432" # Outstide the container, the host, which connects with the psql/ inside the container
